version: "3.0"

services:
  app:
    build: .
    restart: always
    environment:
      BOT_TOKEN: $BOT_TOKEN
      DATABASE_URI: $DATABASE_URI
      ADMIN_USER_IDS: $ADMIN_USER_IDS
    volumes:
      - ./data:/app/data